#pragma once

#include "travelingsalesmansolver/algorithm_formatter.hpp"
#include "travelingsalesmansolver/solution_builder.hpp"
#include "travelingsalesmansolver/candidates/nearest_neighbor.hpp"
#include "travelingsalesmansolver/algorithms/random_permutation.hpp"
#include "travelingsalesmansolver/algorithms/two_opt.hpp"
#include "travelingsalesmansolver/algorithms/random_walk.hpp"
#include "travelingsalesmansolver/algorithms/lin_kernighan.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <numeric>
#include <random>
#include <vector>

namespace travelingsalesmansolver
{

struct EaxParameters: Parameters
{
    /** Number of individuals of the population. */
    int population_size = 300;

    /** Number of offspring solutions generated by each pair of parents. */
    int number_of_children = 30;

    /**
     * Initial tours of the individuals of the initial population:
     * "random-permutation" ('random_permutation') or "random-walk"
     * ('random_walk' on the alpha-nearness candidates, as LKH's initial
     * tours).
     */
    std::string initial_tours = "random-permutation";

    /**
     * Local search applied to the initial tours: "2-opt" ('two_opt' on the 50
     * nearest neighbors), "lin-kernighan" (the first local search of
     * 'lin_kernighan', on the alpha-nearness candidates) or "none".
     */
    std::string initial_local_search = "2-opt";

    /** Number of alpha-nearness candidates (random walks, Lin-Kernighan). */
    VertexId number_of_candidates = 5;

    /**
     * Number of nearest neighbors considered when connecting the subtours of
     * an intermediate solution.
     */
    VertexId number_of_near_vertices = 10;

    /** Run the second stage (block2 strategy). */
    bool stage_2 = true;

    /** Maximum tabu tenure of the block2 strategy. */
    int tabu_maximum_tenure = 10;

    /** Number of iterations without improvement ending the block2 tabu search. */
    int tabu_maximum_number_of_iterations_without_improvement = 20;


    virtual nlohmann::json to_json() const override
    {
        nlohmann::json json = Parameters::to_json();
        json.merge_patch({
                {"PopulationSize", population_size},
                {"NumberOfChildren", number_of_children},
                {"InitialTours", initial_tours},
                {"InitialLocalSearch", initial_local_search},
                {"NumberOfCandidates", number_of_candidates},
                {"NumberOfNearVertices", number_of_near_vertices},
                {"Stage2", stage_2},
                {"TabuMaximumTenure", tabu_maximum_tenure},
                {"TabuMaximumNumberOfIterationsWithoutImprovement", tabu_maximum_number_of_iterations_without_improvement},
                });
        return json;
    }

    virtual int format_width() const override { return 37; }

    virtual void format(std::ostream& os) const override
    {
        Parameters::format(os);
        int width = format_width();
        os
            << std::setw(width) << std::left << "Population size: " << population_size << std::endl
            << std::setw(width) << std::left << "Number of children: " << number_of_children << std::endl
            << std::setw(width) << std::left << "Initial tours: " << initial_tours << std::endl
            << std::setw(width) << std::left << "Initial local search: " << initial_local_search << std::endl
            << std::setw(width) << std::left << "Number of candidates: " << number_of_candidates << std::endl
            << std::setw(width) << std::left << "Number of near vertices: " << number_of_near_vertices << std::endl
            << std::setw(width) << std::left << "Stage 2: " << stage_2 << std::endl
            << std::setw(width) << std::left << "Tabu maximum tenure: " << tabu_maximum_tenure << std::endl
            << std::setw(width) << std::left << "Tabu stagnation: " << tabu_maximum_number_of_iterations_without_improvement << std::endl
            ;
    }
};

/**
 * Genetic algorithm with edge assembly crossover (EAX), as described by
 * Nagata and Kobayashi, "A Powerful Genetic Algorithm Using Edge Assembly
 * Crossover for the Traveling Salesman Problem", INFORMS Journal on
 * Computing, 2013.
 *
 * The initial population consists of random permutations improved by a
 * 2-opt ('two_opt'), by default (see 'EaxParameters::initial_tours' and
 * 'initial_local_search'). In each generation, each individual is the first parent
 * (pA) once, with a random second parent (pB); EAX generates offspring
 * solutions from them, and the best one (entropy-preserving selection)
 * replaces pA if it's better. Stage I uses EAX with the single strategy
 * (localized EAX), stage II EAX with the block2 strategy.
 */
const Output eax(
        const Instance& instance,
        std::mt19937_64& generator,
        const EaxParameters& parameters = {});

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

namespace eax_internal
{

/** Tour: the two neighbors of each vertex, and the length. */
struct Tour
{
    std::vector<std::array<VertexId, 2>> neighbors;

    Distance length = 0;

    /**
     * Order of the vertices along the tour, and position of each vertex
     * (valid if 'order_valid': computed when the tour is a first parent, and
     * kept until it's modified).
     */
    std::vector<int32_t> order;
    std::vector<int32_t> positions;
    bool order_valid = false;
};

/**
 * Number of individuals of the population containing each edge: for each
 * vertex, the list of the other ends of its edges in the population, with
 * their counts (a few entries per vertex).
 */
class EdgeFrequencies
{

public:

    EdgeFrequencies(VertexId number_of_vertices):
        lists_(number_of_vertices) { }

    inline int64_t get(VertexId vertex_id_1, VertexId vertex_id_2) const
    {
        for (const auto& entry: lists_[vertex_id_1])
            if (entry.first == vertex_id_2)
                return entry.second;
        return 0;
    }

    void add(VertexId vertex_id_1, VertexId vertex_id_2, int64_t delta)
    {
        add_directed(vertex_id_1, vertex_id_2, delta);
        add_directed(vertex_id_2, vertex_id_1, delta);
    }

private:

    void add_directed(VertexId vertex_id_1, VertexId vertex_id_2, int64_t delta)
    {
        auto& list = lists_[vertex_id_1];
        for (size_t pos = 0; pos < list.size(); ++pos) {
            if (list[pos].first == vertex_id_2) {
                list[pos].second += delta;
                if (list[pos].second == 0) {
                    list[pos] = list.back();
                    list.pop_back();
                }
                return;
            }
        }
        list.push_back({vertex_id_2, delta});
    }

    std::vector<std::vector<std::pair<VertexId, int64_t>>> lists_;
};

/** Edge, with its ends sorted. */
struct Edge
{
    VertexId vertex_id_1 = -1;
    VertexId vertex_id_2 = -1;

    Edge() = default;

    Edge(VertexId a, VertexId b):
        vertex_id_1(std::min(a, b)),
        vertex_id_2(std::max(a, b)) { }

    bool operator<(const Edge& edge) const
    {
        return (vertex_id_1 != edge.vertex_id_1)?
            vertex_id_1 < edge.vertex_id_1:
            vertex_id_2 < edge.vertex_id_2;
    }

    bool operator==(const Edge& edge) const
    {
        return vertex_id_1 == edge.vertex_id_1 && vertex_id_2 == edge.vertex_id_2;
    }
};

/** Offspring solution: the edges removed from and added to pA. */
struct Offspring
{
    std::vector<Edge> removed_edges;

    std::vector<Edge> added_edges;

    /** Difference of tour length with pA. */
    Distance length_difference = 0;

    /** Evaluation (entropy-preserving selection). */
    double evaluation = 0;
};

}

}
