#pragma once

#include "travelingsalesmansolver/algorithm_formatter.hpp"

#include <random>

namespace travelingsalesmansolver
{

struct EaxParameters: Parameters
{
    /** Number of individuals of the population. */
    int population_size = 300;

    /** Number of offspring solutions generated by each pair of parents. */
    int number_of_children = 30;

    /**
     * Initial tours of the individuals of the initial population:
     * "random-permutation" ('random_permutation') or "random-walk"
     * ('random_walk' on the alpha-nearness candidates, as LKH's initial
     * tours).
     */
    std::string initial_tours = "random-permutation";

    /**
     * Local search applied to the initial tours: "2-opt" ('two_opt' on the 50
     * nearest neighbors), "lin-kernighan" (the first local search of
     * 'lin_kernighan', on the alpha-nearness candidates) or "none".
     */
    std::string initial_local_search = "2-opt";

    /** Number of alpha-nearness candidates (random walks, Lin-Kernighan). */
    VertexId number_of_candidates = 5;

    /**
     * Number of nearest neighbors considered when connecting the subtours of
     * an intermediate solution.
     */
    VertexId number_of_near_vertices = 10;

    /** Run the second stage (block2 strategy). */
    bool stage_2 = true;

    /** Maximum tabu tenure of the block2 strategy. */
    int tabu_maximum_tenure = 10;

    /** Number of iterations without improvement ending the block2 tabu search. */
    int tabu_maximum_number_of_iterations_without_improvement = 20;


    virtual nlohmann::json to_json() const override
    {
        nlohmann::json json = Parameters::to_json();
        json.merge_patch({
                {"PopulationSize", population_size},
                {"NumberOfChildren", number_of_children},
                {"InitialTours", initial_tours},
                {"InitialLocalSearch", initial_local_search},
                {"NumberOfCandidates", number_of_candidates},
                {"NumberOfNearVertices", number_of_near_vertices},
                {"Stage2", stage_2},
                {"TabuMaximumTenure", tabu_maximum_tenure},
                {"TabuMaximumNumberOfIterationsWithoutImprovement", tabu_maximum_number_of_iterations_without_improvement},
                });
        return json;
    }

    virtual int format_width() const override { return 37; }

    virtual void format(std::ostream& os) const override
    {
        Parameters::format(os);
        int width = format_width();
        os
            << std::setw(width) << std::left << "Population size: " << population_size << std::endl
            << std::setw(width) << std::left << "Number of children: " << number_of_children << std::endl
            << std::setw(width) << std::left << "Initial tours: " << initial_tours << std::endl
            << std::setw(width) << std::left << "Initial local search: " << initial_local_search << std::endl
            << std::setw(width) << std::left << "Number of candidates: " << number_of_candidates << std::endl
            << std::setw(width) << std::left << "Number of near vertices: " << number_of_near_vertices << std::endl
            << std::setw(width) << std::left << "Stage 2: " << stage_2 << std::endl
            << std::setw(width) << std::left << "Tabu maximum tenure: " << tabu_maximum_tenure << std::endl
            << std::setw(width) << std::left << "Tabu stagnation: " << tabu_maximum_number_of_iterations_without_improvement << std::endl
            ;
    }
};

/**
 * Genetic algorithm with edge assembly crossover (EAX), as described by
 * Nagata and Kobayashi, "A Powerful Genetic Algorithm Using Edge Assembly
 * Crossover for the Traveling Salesman Problem", INFORMS Journal on
 * Computing, 2013.
 *
 * The initial population consists of random permutations improved by a
 * 2-opt ('two_opt'), by default (see 'EaxParameters::initial_tours' and
 * 'initial_local_search'). In each generation, each individual is the first parent
 * (pA) once, with a random second parent (pB); EAX generates offspring
 * solutions from them, and the best one (entropy-preserving selection)
 * replaces pA if it's better. Stage I uses EAX with the single strategy
 * (localized EAX), stage II EAX with the block2 strategy.
 */
const Output eax(
        const Instance& instance,
        std::mt19937_64& generator,
        const EaxParameters& parameters = {});

}
