load("//travelingsalesmansolver:variables.bzl", "STDCPP")

cc_library(
        name = "concorde",
        hdrs = ["concorde.hpp"],
        srcs = ["concorde.cpp"],
        copts = STDCPP,
        deps = ["//travelingsalesmansolver:travelingsalesmansolver"],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "lkh",
        hdrs = ["lkh.hpp"],
        srcs = ["lkh.cpp"],
        copts = STDCPP,
        deps = ["//travelingsalesmansolver:travelingsalesmansolver"],
        visibility = ["//visibility:public"],
)
